[package]
name = "lis2dw12"
version = "0.1.0"
authors = ["David Haig <david@ninjametal.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.5"
accelerometer = "0.12.0"

[profile.release]
lto = true

