[package]
name = "lis2dw12"
version = "0.1.0"
authors = ["David Haig <david@ninjametal.com>"]
edition = "2018"

[features]
default = []
out_f32 = ["num-traits", "num-derive"]

[dependencies]
embedded-hal = "0.2.5"
accelerometer = "0.12.0"
num-traits = { version = "0.2.14", optional = true }
num-derive = { version = "0.3.3", optional = true }
cast = { version = "0.2.5", default-features = false }

[profile.release]
lto = true

